name: Release on GitHub

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix build -L
      - run: ls -l result/
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG}}" ${{ env.TAG }} result/*.ova
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
